application.name: @project.name@
application.title: Technical Development Solutions
application.version: @project.version@
application.buildNumber: @buildNumber@
application.buildDateTime: @timestamp@

spring.datasource.url: jdbc:mysql://ubuntu-filekit-01:3306/seed
spring.datasource.username: chris
spring.datasource.password: abcABC123!@#
spring.datasource.driver-class-name: com.mysql.jdbc.Driver